### ISSUE TITLE
Support for ClamAV Version 1.0?

### ISSUE THREAD

**Issue by 15Cyndaquil** [tquizzle/clamav-alpine#12]
Recently I've been getting this error while scanning some files

```
LibClamAV Warning: crtmgr_rsa_verify: verification failed: fp_exptmod failed with 1
```

Looks like it was addressed in ClamAV itself with in issue here: https://github.com/Cisco-Talos/clamav/issues/604

Only problem with that is that it looks like the merge is only going to be supported for version 1.0 as per this merge from October: https://github.com/Cisco-Talos/clamav/pull/727#issuecomment-1287550983

So was mainly wondering if there are any current plans to or if it would be feasible to add support for/update to ClamAV Version 1.0?

**Comment by tquizzle** [comment]
I can't really say. This container is based on an Alpine Linux OS. I follow it pretty frequently, but it doesn't appear to be updating to the 1. branch.
The most recent version is 0.105.2-r0, which I updated.

**Comment by tquizzle** [comment]
@15Cyndaquil I was able to update to 1.0.1 in the `edge` branch. Let me know if that solves the issue.

**Comment by 15Cyndaquil** [comment]
This has solved my issue. Thank you!
