### ISSUE TITLE
Critical error with current release

### ISSUE THREAD

**Issue by wgstarks** [tquizzle/clamav-alpine#3]
I posted this error in the support thread but thought it wouldn’t hurt to post the issue here as well. After the most recent update I’m getting this error flooding my logs-
`LibClamAV Error: CRITICAL: fmap() failed `

I still get notifications that the scan completed successfully even though it appears to be failing.

There are multiple reports of this in the support thread. It seems to have been an issue which was fixed previously in ClamAV but perhaps there is some regression?

**Comment by Aceriz** [comment]
Following .  Also getting same error

**Comment by CaptInsano** [comment]
Following also, same issue here

**Comment by techie2000** [comment]
Checked my logs and can confirm similar postings at various points in a lengthy scan session

Small selection:
```
  | 2021-03-24 01:38:01 | LibClamAV Warning: fmap: failed to get MD5
  | 2021-03-24 01:38:01 | LibClamAV Error: CRITICAL: fmap() failed
  | 2021-03-24 01:38:01 | LibClamAV Warning: fmap: failed to get MD5
  | 2021-03-24 01:38:01 | LibClamAV Error: CRITICAL: fmap() failed
  | 2021-03-24 01:38:01 | LibClamAV Warning: fmap: failed to get MD5
  | 2021-03-24 01:38:01 | LibClamAV Error: CRITICAL: fmap() failed
  | 2021-03-24 01:38:01 | LibClamAV Warning: fmap: failed to get MD5
  | 2021-03-24 01:38:01 | LibClamAV Error: CRITICAL: fmap() failed
  | 2021-03-24 01:38:01 | LibClamAV Warning: fmap: failed to get MD5
  | 2021-03-24 01:38:01 | LibClamAV Error: CRITICAL: fmap() failed
  | 2021-03-24 01:38:01 | LibClamAV Warning: fmap: failed to get MD5
  | 2021-03-24 01:38:01 | LibClamAV Error: CRITICAL: fmap() failed
  | 2021-03-24 01:37:58 | LibClamAV Warning: fmap: failed to get MD5
  | 2021-03-24 01:37:58 | LibClamAV Error: CRITICAL: fmap() failed
  | 2021-03-24 01:37:40 | LibClamAV Warning: fmap: failed to get MD5
  | 2021-03-24 01:37:40 | LibClamAV Error: CRITICAL: fmap() failed
  | 2021-03-24 01:37:07 | LibClamAV Warning: fmap: failed to get MD5
  | 2021-03-24 01:37:07 | LibClamAV Error: CRITICAL: fmap() failed
  | 2021-03-24 01:36:38 | LibClamAV Warning: fmap: failed to get MD5
  | 2021-03-24 01:36:38 | LibClamAV Error: CRITICAL: fmap() failed
  | 2021-03-24 01:36:23 | LibClamAV Warning: fmap: failed to get MD5
  | 2021-03-24 01:36:23 | LibClamAV Error: CRITICAL: fmap() failed
  | 2021-03-24 01:36:20 | LibClamAV Warning: fmap: failed to get MD5
  | 2021-03-24 01:36:20 | LibClamAV Error: CRITICAL: fmap() failed
  | 2021-03-24 01:35:58 | LibClamAV Warning: fmap: failed to get MD5
```

However, on doing a bit of research, it appears to have been going on for years [https://bugzilla.clamav.net/show_bug.cgi?id=10971](https://bugzilla.clamav.net/show_bug.cgi?id=10971) and not something for the docker owner to worry about?

**Comment by tquizzle** [comment]
That's my understanding @techie2000.
Related to memory and size of file.

I've tried limiting the size of the file scanned, but it still gives me some issues.

**Comment by tquizzle** [comment]
Bumped to the latest version and tested it today. 
No `LibClamAV` error.
Please test and let me know.

**Comment by techie2000** [comment]
> Please test and let me know.

I've just kicked off a manual background job. Will check the logs our later and report back

**Comment by techie2000** [comment]
Apologies for (very) late follow up. I ca confirm I have no seen any more occurrences of this 'CRTICAL' error.
I noticed a few warning on my last scan, but I'm not overly worried by them:

```
  | 2021-05-01 15:14:41 | LibClamAV Warning: Bytecode run timed out in interpreter after 5000 opcodes
  | 2021-05-01 15:14:41 | LibClamAV Warning: Bytecode 78 failed to run: CL_ETIMEOUT: Time limit reached
  | 2021-05-01 15:07:15 | LibClamAV Warning: Bytecode run timed out in interpreter after 10000 opcodes
  | 2021-05-01 15:07:15 | LibClamAV Warning: Bytecode 78 failed to run: CL_ETIMEOUT: Time limit reached
  | 2021-05-01 15:01:11 | LibClamAV Warning: Bytecode run timed out in interpreter after 15000 opcodes
  | 2021-05-01 15:01:11 | LibClamAV Warning: Bytecode 78 failed to run: CL_ETIMEOUT: Time limit reached
  | 2021-05-01 14:32:10 | LibClamAV Warning: Bytecode run timed out in interpreter after 15000 opcodes
  | 2021-05-01 14:32:10 | LibClamAV Warning: Bytecode 78 failed to run: CL_ETIMEOUT: Time limit reached
  | 2021-05-01 14:23:18 | LibClamAV Warning: Bytecode run timed out in interpreter after 70000 opcodes
  | 2021-05-01 14:23:18 | LibClamAV Warning: Bytecode 78 failed to run: CL_ETIMEOUT: Time limit reached
  | 2021-05-01 06:47:50 | LibClamAV Warning: Bytecode 78 failed to run: CL_ETIMEOUT: Time limit reached
  | 2021-05-01 06:47:50 | LibClamAV Warning: Bytecode run timed out in interpreter after 5000 opcodes
```
and prior to that

```

  | 2021-04-30 07:13:22 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:22 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:22 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:22 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:21 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:21 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:21 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:21 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:20 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:20 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:20 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:20 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:20 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:20 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:19 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:19 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:18 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:18 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:16 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:13:16 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:12:58 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
  | 2021-04-30 07:12:58 | LibClamAV Warning: Partial message received from MUA/MTA - message cannot be scanned
```

**Comment by tquizzle** [comment]
Ok  @techie2000, I think I have found some information that might help.

> Bytecode signatures are a specialized type of ClamAV signature which is able to perform additional processing of the scanned file and allow for more robust detection. Unlike the standard ClamAV signature types, bytecode signatures have a number of unique distinctions which need to be respected for their effective usage.

Trust

> Bytecode signatures, by default, are considered untrusted. In fact, only bytecode signatures published by Cisco, in the bytecode.cvd are considered “trusted”. This means that the ClamAV engine will, by default, never load, trigger or execute untrusted bytecodes. One can bypass this safety mechanism by specifying the bytecode unsigned option to the engine but it should be noted that it is up to the user’s discretion on using untrusted bytecode signatures.

For clamscan, the command line option is

`--bytecode-unsigned`

Timeout

> Bytecode signatures are designed to only run for a limited amount of time designated by an internal timeout value. If execution time exceeds the value, the bytecode signature’s execution is terminated and the user is notified. The bytecode signature timeout value can be set by the user.

`--bytecode-timeout=[time in ms]`

See if adding those post-args resolves the bytecode issue.
The MUA/MTA issue seems to stem from scanning email messages. I cant find anything definitive other than a bug report filed for this issue.

**Comment by techie2000** [comment]
> See if adding those post-args resolves the bytecode issue.

Thanks @tquizzle I'll add these two settings when I get home. 


> The MUA/MTA issue seems to stem from scanning email messages. I cant find anything definitive other than a bug report filed for this issue.

As background, my setup is a headerless box sans of email.

**Comment by adampblack** [comment]
I just tried:
`sudo clamscan -r -i --remove --bytecode-unsigned --bytecode-timeout=1000000 / > ~/20210715_clamav_remove_output.txt`

Still getting the error message:
`LibClamAV Warning: fmap_readpage: pread fail: asked for 4093 bytes @ offset 3, got 0
LibClamAV Warning: fmap: failed to get MD5`

**Comment by adampblack** [comment]
FYI, I tried changing -i to -o as suggested here:
https://www.mail-archive.com/clamav-users@lists.clamav.net/msg49945.html

no luck

**Comment by adampblack** [comment]
Some people suggest that large files are the issue (perhaps the old 32bit limit of 4gb):
https://stackoverflow.com/questions/34076184/clamscan-not-skipping-large-files-and-has-fmap-error

Still getting the same error when I limit the max file size:
`sudo clamscan -r -o --max-filesize=100k --remove  / > ~/20210715_clamav_remove_output.txt`

I could suppress the warning by:
--quiet                              Only output error messages


But it still was coming up with warning messages!

The issue seems to be folder/file dependent - it seemed to work fine just on my home directory but not from the root directory.

sudo clamscan -r clamscan_investigation ~/ --quiet > ~/20210715_clamav_investigation_output.txt

**Comment by adampblack** [comment]
@tquizzle the last comment is the last time I have used the software - so if there has been no release history addressing the issue the problem still exists.

I think there server was running **Ubuntu 18.04** and **apache webserver** if this helps.

**Comment by TheZLabs** [comment]
I was getting the same errors. Fixed it by running the command this way:
sudo clamscan -ir --exclude-dir=^/sys --exclude-dir=^/dev --exclude-dir=^/proc

**Comment by tquizzle** [comment]
In that case, are you mounting the scan directory to be the `/` of the system? If so, yeah, you will absolutely need to exclude the typical directories that the clam and clamd packages would do by default.

**Comment by tquizzle** [comment]
All images updated.
All images scanned and updated packages that were vulnerable.
