### ISSUE TITLE
max file size doesn't work in post arguments

### ISSUE THREAD

**Issue by twist3dimages** [tquizzle/clamav-alpine#34]
logs:

08/12/2023 7:11:19 PM
ERROR: Incorrect argument format for option --max-filesize
08/12/2023 7:11:19 PM
ERROR: Can't parse command line options

my command line is 

-i --cross-fs=yes -alert-encrypted=yes --max-filesize=2G  --move /infected --bell

**Comment by tquizzle** [comment]
At first glance, your `-alert-encrypted` needs two hyphens.
https://docs.clamav.net/manual/Usage/Scanning.html#clamscan

**Comment by tquizzle** [comment]
Digging into that, the default is `20M`; however, the `--max-filesize` also tops out at 4G. Not sure why it wouldn't work.

Try `--max-scansize=` in MB instead.

**Comment by twist3dimages** [comment]
--max-scansize=500M worked thanks!

**Comment by tquizzle** [comment]
Awesome!
