### ISSUE TITLE
Unraid: Icon Url is not valid anymore

### ISSUE THREAD

**Issue by UNRA1DUser** [tquizzle/clamav-alpine#46]
Hi,

can you please update the Icon Url for Unraid? It´s not valid anymore.

NEW VALUE: https://raw.githubusercontent.com/tquizzle/clamav-alpine/master/img/clamav.png

and if you add "--user=99:100" to the Extra Parameters:  you don´t need to do any manually permission changes on the filesystem itself anymore. The Docker App would work directly without any changes.

Thanks!

**Comment by tquizzle** [comment]
Thanks for that! Updated in unraid xml repo.
Community Apps should pick it up soon.

**Comment by tquizzle** [comment]
Looks like CA picked up the changes in the icon. 
I will also add the verbiage for the user parameter you mentioned.
