### ISSUE TITLE
Use of optional parameter?

### ISSUE THREAD

**Issue by techie2000** [tquizzle/clamav-alpine#7]
Can you expose an optional parameter `--file-list=FILE` - scan files from FILE? More details on [https://www.clamav.net/documents/scanning](https://www.clamav.net/documents/scanning)

Why? I have multiple /mnt/points/and/many/folders/hundreds of thousands of files/ and would ideally define a file which contains the much smaller subset of /mnt/point/folders I want to have scanned.

Currently it takes over a day to scan all the files and thrashes my poor drives for the duration!

**Comment by tquizzle** [comment]
Updated the docs - you can modify that in your usage of the post-args.
