### ISSUE TITLE
[Question] How would I give my pc/Docker more time to pull the database?

### ISSUE THREAD

**Issue by Tom284** [tquizzle/clamav-alpine#8]
Every time I build the database it seems like the container gets stuck at a different place when pulling the database.

Example:
`Time: 4.7s, ETA: 4.0s [=============> ] 55.22MiB/101.46MiB`
Personally I think that this has to do with the connection timeout. How would I increase for example the `ReceiveTimeout ` proptery from the config?

This only happens when I build my own image. When I pull this image:
`docker run -it -v /opt:/scan:ro tquinnelly/clamav-alpine -i`
The download does get completed. But I would like to make my own Image.

**Comment by tquizzle** [comment]
Unfortunately, I am not sure.

If I understand correctly you are adding the Clam DBs into your image?
I would caution against this because within a day your image would be out of date.

**Comment by Tom284** [comment]
I believe that I am indeed pulling the database. But that is what happens when I build the image from the repo. The same happens when I build the already existing image. 
How would I not do this and keep my DB up-to-date?

**Comment by tquizzle** [comment]
You shouldn't have to, no.
